### DISCUSSION TITLE
Multiline command

### DISCUSSION THREAD

**Discussion by ret1nol** [ovidiuvio/VSDebugPro#43] [General]
Is it possible to make support for multi-line commands?
![image](https://user-images.githubusercontent.com/8386329/54986378-96478f80-4fc3-11e9-9185-2bdc2200229f.png)

**Comment by ovidiuvio** [comment]
There is a python branch under development that integrates iron python as a scripting engine.
It should be fairly easily to achieve the above with a python script.

However development for python scripting is still on going and not stable yet.

**Comment by ovidiuvio** [comment]
You can do this now with the exec command:
https://www.vsdebug.pro/pages/docs/exec.html

```yaml
variables:
  # 'buffer' is evaluated at runtime in debug engine api
  ptr_base: "buffer"
  # 'segmentSize' variable will be valuated at execution time in debug engine api
  size: "segmentSize"
  # expressions don't support spaces. 'buffer+(0*segmentSize)' is evaluated later in debug engine api
  # ptr_base mustache variable will be replaced  with 'buffer'
  segData0: "{{ptr_base}}+(0*segmentSize)"
  segFile0: "segment0.bin"
  # expressions don't support spaces.
  segData1: "{{ptr_base}}+(1*segmentSize)"
  segFile1: "segment1.bin"
  # expressions don't support spaces.
  segData2: "{{ptr_base}}+(2*segmentSize)"
  segFile2: "segment2.bin"

commands:
  - dumpmem -f {{segFile0}} {{segData0}} {{size}}
  - dumpmem -f {{segFile1}} {{segData1}} {{size}}
  - dumpmem -f {{segFile2}} {{segData2}} {{size}}
  - dumpmem -a segments.bin {{segData2}} {{size}}
  - dumpmem -a segments.bin {{segData1}} {{size}}
  - dumpmem -a segments.bin {{segData0}} {{size}}
```
